# Remove Comments and Re-run `yarn` to Fix `ts-loader` bug
# packageExtensions:
#   "ts-loader@*":
#     peerDependencies:
#       webpack: "*"

# Remove Comments and Re-run `yarn` to Fix `webpack-cli` bug
# packageExtensions:
#   "webpack-cli@*":
#     optionalDependencies:
#       webpack-dev-server: "*"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
